postgres:
  image: postgres
  environment:
    - POSTGRES_DATABASE=keycloak
    - POSTGRES_USER=keycloak
    - POSTGRES_PASSWORD=password
    - POSTGRES_ROOT_PASSWORD=root_password

keycloak:
  image: jboss/keycloak-postgres
  links:
    - postgres:postgres
  environment:
    - POSTGRES_DATABASE=keycloak
    - POSTGRES_USER=keycloak
    - POSTGRES_PASSWORD=password
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
  volumes:
    - ./themes:/opt/jboss/keycloak/themes/
  ports:
    - "8080:8080"
