export const KEYCLOAK_INIT_SUCCESS = "KEYCLOAK_INIT_SUCCESS";
export const CONFIGFILE_LOAD_SUCCESS = "CONFIGFILE_LOAD_SUCCESS";
export const CONFIGFILE_LOAD_FAILED = "CONFIGFILE_LOAD_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const ACCOUNT_REDIRECT_SUCCESS = "ACCOUNT_REDIRECT_SUCCESS";
export const BASEENTITIES_LOAD_SUCCESS = "BASEENTITIES_LOAD_SUCCESS";
export const ASKS_LOAD_SUCCESS = "ASKS_LOAD_SUCCESS";


